// Shell-completion script generator for the cchist CLI.
//
// Static completion only — we enumerate the commander program tree once and
// emit a script that knows the command/option surface. Dynamic completion
// (session ids, file paths) is intentionally out of scope; that lives behind
// each shell's `_files` / glob primitives if/when we extend later.

import { type Command } from "commander";

export type OptionInfo = {
  /** Long flag including leading dashes, e.g. "--source". null if short-only. */
  long: string | null;
  /** Short flag, e.g. "-h". null if not defined. */
  short: string | null;
  /** Human-readable description (single line; may be empty). */
  description: string;
  /** Allowed values when `.choices([...])` is used; empty array otherwise. */
  choices: string[];
  /** True for `--foo <bar>` / `--foo [bar]` style; false for boolean flags. */
  takesValue: boolean;
};

export type CommandInfo = {
  /** Path from program root, e.g. ["sessions", "list"]. Never empty. */
  path: string[];
  /** Subcommand summary line (commander `.description()`). */
  description: string;
  options: OptionInfo[];
  /** Names of direct child subcommands (sorted), so generators can branch on depth. */
  subcommands: string[];
};

/** Walk a commander Command tree into a flat list, skipping the root program itself. */
export function flattenCommands(root: Command): CommandInfo[] {
  const out: CommandInfo[] = [];
  walk(root, [], out);
  return out;
}

function walk(cmd: Command, prefix: string[], out: CommandInfo[]): void {
  // Root program (prefix empty) isn't a "subcommand"; only descend.
  if (prefix.length > 0) {
    const subs = cmd.commands.map((c) => c.name()).sort();
    out.push({
      path: prefix,
      description: (cmd.description() || "").trim(),
      options: cmd.options.map(toOptionInfo),
      subcommands: subs,
    });
  }
  for (const sub of cmd.commands) {
    walk(sub, [...prefix, sub.name()], out);
  }
}

function toOptionInfo(o: unknown): OptionInfo {
  // commander's Option fields are not formally typed via its public API surface,
  // but the documented runtime shape is stable (long/short/description/argChoices/flags).
  const opt = o as {
    long?: string | null;
    short?: string | null;
    description?: string;
    argChoices?: readonly string[];
    flags?: string;
  };
  const flags = String(opt.flags ?? "");
  return {
    long: opt.long ?? null,
    short: opt.short ?? null,
    description: (opt.description ?? "").trim(),
    choices: Array.isArray(opt.argChoices) ? [...opt.argChoices] : [],
    takesValue: /[<[]/.test(flags),
  };
}

/** All flag tokens (long preferred, short kept too) sorted for stable output. */
function flagTokens(opt: OptionInfo): string[] {
  const t: string[] = [];
  if (opt.long) t.push(opt.long);
  if (opt.short) t.push(opt.short);
  return t;
}

// ----- bash --------------------------------------------------------------

export function buildBashCompletion(cmds: CommandInfo[], programName = "cchist"): string {
  const top = cmds
    .filter((c) => c.path.length === 1)
    .map((c) => c.path[0]!)
    .sort();

  // Per first-level subcommand: child subcommands (if any) and own options.
  const lines: string[] = [];
  lines.push(
    `# bash completion for ${programName} — generated by \`${programName} completion bash\``,
  );
  lines.push(`_${programName}() {`);
  lines.push(`  local cur prev`);
  lines.push(`  cur="\${COMP_WORDS[COMP_CWORD]}"`);
  lines.push(`  prev="\${COMP_WORDS[COMP_CWORD-1]:-}"`);
  lines.push(``);
  lines.push(`  # Top-level subcommand`);
  lines.push(`  if [[ $COMP_CWORD -eq 1 ]]; then`);
  lines.push(`    COMPREPLY=( $(compgen -W "${top.join(" ")} --help --version" -- "$cur") )`);
  lines.push(`    return`);
  lines.push(`  fi`);
  lines.push(``);

  const oneLevel = cmds.filter((c) => c.path.length === 1);
  for (const cmd of oneLevel) {
    const name = cmd.path[0]!;
    if (cmd.subcommands.length > 0) {
      lines.push(`  if [[ $COMP_CWORD -eq 2 && "\${COMP_WORDS[1]}" == "${name}" ]]; then`);
      lines.push(`    COMPREPLY=( $(compgen -W "${cmd.subcommands.join(" ")} --help" -- "$cur") )`);
      lines.push(`    return`);
      lines.push(`  fi`);
    }
  }

  lines.push(``);
  lines.push(`  # Options for the currently-resolved command path`);
  lines.push(`  if [[ "$cur" == -* ]]; then`);
  lines.push(`    local opts=""`);
  lines.push(`    case "\${COMP_WORDS[1]:-}" in`);
  for (const cmd of oneLevel) {
    const name = cmd.path[0]!;
    if (cmd.subcommands.length > 0) {
      lines.push(`      ${name})`);
      lines.push(`        case "\${COMP_WORDS[2]:-}" in`);
      const children = cmds.filter((c) => c.path.length === 2 && c.path[0] === name);
      for (const child of children) {
        const childName = child.path[1]!;
        const childOpts = child.options.flatMap(flagTokens).join(" ");
        lines.push(`          ${childName}) opts="${childOpts} --help" ;;`);
      }
      lines.push(`        esac`);
      lines.push(`        ;;`);
    } else {
      const ownOpts = cmd.options.flatMap(flagTokens).join(" ");
      lines.push(`      ${name}) opts="${ownOpts} --help" ;;`);
    }
  }
  lines.push(`    esac`);
  lines.push(`    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )`);
  lines.push(`    return`);
  lines.push(`  fi`);
  lines.push(`}`);
  lines.push(`complete -F _${programName} ${programName}`);
  lines.push(``);
  return lines.join("\n");
}

// ----- zsh ---------------------------------------------------------------

export function buildZshCompletion(cmds: CommandInfo[], programName = "cchist"): string {
  const oneLevel = cmds.filter((c) => c.path.length === 1);

  const lines: string[] = [];
  lines.push(`#compdef ${programName}`);
  lines.push(
    `# zsh completion for ${programName} — generated by \`${programName} completion zsh\``,
  );
  lines.push(``);
  lines.push(`_${programName}() {`);
  lines.push(`  local context state state_descr line`);
  lines.push(`  typeset -A opt_args`);
  lines.push(``);
  lines.push(`  _arguments -C \\`);
  lines.push(`    '1: :->cmd' \\`);
  lines.push(`    '*::arg:->args'`);
  lines.push(``);
  lines.push(`  case $state in`);
  lines.push(`    cmd)`);
  lines.push(`      local -a top`);
  lines.push(`      top=(`);
  for (const c of oneLevel) {
    lines.push(`        '${c.path[0]}:${zshEscape(c.description)}'`);
  }
  lines.push(`      )`);
  lines.push(`      _describe -t commands 'subcommand' top`);
  lines.push(`      ;;`);
  lines.push(`    args)`);
  lines.push(`      case $words[1] in`);
  for (const cmd of oneLevel) {
    const name = cmd.path[0]!;
    lines.push(`        ${name})`);
    if (cmd.subcommands.length > 0) {
      lines.push(`          _arguments -C \\`);
      lines.push(`            '1: :->subcmd' \\`);
      lines.push(`            '*::subargs:->subargs'`);
      lines.push(`          case $state in`);
      lines.push(`            subcmd)`);
      lines.push(`              local -a subs`);
      lines.push(`              subs=(`);
      const children = cmds.filter((c) => c.path.length === 2 && c.path[0] === name);
      for (const child of children) {
        lines.push(`                '${child.path[1]}:${zshEscape(child.description)}'`);
      }
      lines.push(`              )`);
      lines.push(`              _describe -t commands 'subcommand' subs`);
      lines.push(`              ;;`);
      lines.push(`            subargs)`);
      lines.push(`              case $words[1] in`);
      for (const child of children) {
        const childName = child.path[1]!;
        lines.push(`                ${childName})`);
        emitZshOptionArgs(child.options, lines, "                  ");
        lines.push(`                  ;;`);
      }
      lines.push(`              esac`);
      lines.push(`              ;;`);
      lines.push(`          esac`);
    } else {
      emitZshOptionArgs(cmd.options, lines, "          ");
    }
    lines.push(`          ;;`);
  }
  lines.push(`      esac`);
  lines.push(`      ;;`);
  lines.push(`  esac`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`_${programName} "$@"`);
  lines.push(``);
  return lines.join("\n");
}

function emitZshOptionArgs(options: OptionInfo[], lines: string[], indent: string): void {
  if (options.length === 0) {
    lines.push(`${indent}_message 'no options'`);
    return;
  }
  lines.push(`${indent}_arguments \\`);
  const tokens: string[] = [];
  for (const opt of options) {
    const flag = opt.long ?? opt.short;
    if (!flag) continue;
    const desc = zshEscape(opt.description);
    if (opt.choices.length > 0) {
      // Choice-aware completion: zsh syntax is `'--foo[desc]:label:(a b c)'`.
      tokens.push(`'${flag}[${desc}]:value:(${opt.choices.join(" ")})'`);
    } else if (opt.takesValue) {
      tokens.push(`'${flag}[${desc}]:value:'`);
    } else {
      tokens.push(`'${flag}[${desc}]'`);
    }
  }
  lines.push(tokens.map((t) => `${indent}  ${t}`).join(" \\\n"));
}

function zshEscape(s: string): string {
  // Single-quoted zsh strings can't contain `'` or `[`/`]` cleanly; replace.
  return s.replace(/'/g, "").replace(/\[/g, "(").replace(/\]/g, ")");
}

// ----- fish --------------------------------------------------------------

export function buildFishCompletion(cmds: CommandInfo[], programName = "cchist"): string {
  const oneLevel = cmds.filter((c) => c.path.length === 1);
  const lines: string[] = [];
  lines.push(
    `# fish completion for ${programName} — generated by \`${programName} completion fish\``,
  );
  lines.push(``);

  // Top-level subcommands
  for (const c of oneLevel) {
    lines.push(
      `complete -c ${programName} -n '__fish_use_subcommand' -a ${c.path[0]} -d ${fishQ(c.description)}`,
    );
  }
  lines.push(``);

  // Nested subcommands and per-command options
  for (const cmd of oneLevel) {
    const name = cmd.path[0]!;
    if (cmd.subcommands.length > 0) {
      const children = cmds.filter((c) => c.path.length === 2 && c.path[0] === name);
      for (const child of children) {
        const childName = child.path[1]!;
        lines.push(
          `complete -c ${programName} -n '__fish_seen_subcommand_from ${name}; and not __fish_seen_subcommand_from ${cmd.subcommands.join(" ")}' -a ${childName} -d ${fishQ(child.description)}`,
        );
        for (const opt of child.options) {
          lines.push(fishOptionLine(programName, `__fish_seen_subcommand_from ${childName}`, opt));
        }
      }
    } else {
      for (const opt of cmd.options) {
        lines.push(fishOptionLine(programName, `__fish_seen_subcommand_from ${name}`, opt));
      }
    }
  }
  lines.push(``);
  return lines.join("\n");
}

function fishOptionLine(programName: string, condition: string, opt: OptionInfo): string {
  const parts = [`complete -c ${programName} -n '${condition}'`];
  if (opt.short) parts.push(`-s ${opt.short.replace(/^-/, "")}`);
  if (opt.long) parts.push(`-l ${opt.long.replace(/^--/, "")}`);
  parts.push(`-d ${fishQ(opt.description)}`);
  if (opt.choices.length > 0) {
    // -x = exclusive (option takes argument), -a = arguments to complete from.
    parts.push(`-x -a ${fishQ(opt.choices.join(" "))}`);
  } else if (opt.takesValue) {
    parts.push(`-r`);
  }
  return parts.join(" ");
}

function fishQ(s: string): string {
  // Fish single-quoted: escape `\` and `'` only.
  return `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}
